notifications:
  email:
    recipients:
      - dpx.infinity@gmail.com

language: rust
sudo: false

rust:
  - nightly
  - beta
  - stable

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  # default travis packages are sufficient to build libejdb
  - |
      git clone https://github.com/Softmotions/ejdb.git && pushd ejdb && 
      mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/prefix ../ &&
      make && make install && 
      export PKG_CONFIG_PATH="$HOME/prefix/lib/pkgconfig" && 
      export LD_LIBRARY_PATH="$HOME/prefix/lib:$LD_LIBRARY_PATH" && 
      popd

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only beta doc

after_success:
  - travis-cargo --only beta doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
