notifications:
  email:
    recipients:
      - dpx.infinity@gmail.com

language: rust
sudo: false

addons:
  apt:
    packages:
      - cmake
      - zlib1g-dev
      - git
      - pkg-config

rust:
  - nightly
  - beta
  - stable

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - |
      git clone https://github.com/Softmotions/ejdb.git &&
      cd ejdb && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/prefix ../ &&
      make && make install &&
      export PKG_CONFIG_PATH=$HOME/prefix/lib/x86_64-linux-gnu/pkgconfig

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only beta doc

after_success:
  - travis-cargo --only beta doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
