notifications:
  email:
    recipients:
      - dpx.infinity@gmail.com

language: rust
sudo: false

rust:
  - nightly
  - beta
  - stable

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only beta doc

after_success:
  - travis-cargo --only beta doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
