[package]
name = "ejdb"
version = "0.1.1"
authors = ["Vladimir Matveev <vladimir.matweev@gmail.com>"]
description = "Bindings for EJDB, and embedded JSON database"
repository = "https://github.com/netvl/ejdb.rs"
documentation = "https://netvl.github.io/ejdb.rs/"
readme = "Readme.md"
keywords = ["ejdb", "database", "json", "bson", "ffi"]
license = "MIT"

[lib]
name = "ejdb"

[dependencies]
ejdb-sys = { path = "ejdb-sys", version = "0.1" }
bson = "0.1"
bitflags = "0.3"
quick-error = "0.1"
libc = "0.1"
itertools = "0.4"

[dev-dependencies]
tempdir = "0.3"
