(function() {var implementors = {};
implementors["ejdb"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"type\" href=\"ejdb/bson/type.Document.html\" title=\"type ejdb::bson::Document\">Document</a>&gt; for <a class=\"struct\" href=\"ejdb/query/struct.QueryHints.html\" title=\"struct ejdb::query::QueryHints\">QueryHints</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"type\" href=\"ejdb/bson/type.Document.html\" title=\"type ejdb::bson::Document\">Document</a>&gt; for <a class=\"struct\" href=\"ejdb/query/struct.Query.html\" title=\"struct ejdb::query::Query\">Query</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"type\" href=\"ejdb_sys/ffi/type.bson_oid_t.html\" title=\"type ejdb_sys::ffi::bson_oid_t\">bson_oid_t</a>&gt; for <a class=\"struct\" href=\"ejdb/ejdb_bson/struct.EjdbObjectId.html\" title=\"struct ejdb::ejdb_bson::EjdbObjectId\">EjdbObjectId</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"ejdb/bson/oid/struct.ObjectId.html\" title=\"struct ejdb::bson::oid::ObjectId\">ObjectId</a>&gt; for <a class=\"struct\" href=\"ejdb/ejdb_bson/struct.EjdbObjectId.html\" title=\"struct ejdb::ejdb_bson::EjdbObjectId\">EjdbObjectId</a>",];
implementors["serde"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt;&gt; for <a class=\"struct\" href=\"serde/bytes/struct.ByteBuf.html\" title=\"struct serde::bytes::ByteBuf\">ByteBuf</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">&amp;'a [</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt; for <a class=\"struct\" href=\"serde/bytes/struct.Bytes.html\" title=\"struct serde::bytes::Bytes\">Bytes</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
